// Writes src/i18n/en/save_ids.js: English -> Chinese for every id that can
// appear in a save exported from the old English build.
//
// The source is that build itself, not anything in this tree. It forked at
// V2.22c and renamed `name` in place; pairing each collection's names against
// its own base is the only record of what its saves actually contain. The
// current glossary is a different, later translation and would disagree.
//
// Needs the maxrau remote, so this is not a `bun run compile` step -- same
// arrangement as extract-translations.ts. Run it by hand; the output is
// committed.

import { mkdirSync, writeFileSync } from "node:fs";
import { join } from "node:path";

const BRANCH = "maxrau/english";
const root = join(import.meta.dir, "..");

function git(...args: string[]) {
    const result = Bun.spawnSync(["git", ...args], { cwd: root });
    if(result.exitCode !== 0) {
        throw new Error(`git ${args.join(" ")}\n${result.stderr.toString()}`);
    }
    return result.stdout.toString();
}

const base = git("merge-base", BRANCH, "main").trim();
const show = (rev: string, file: string) => git("show", `${rev}:src/${file}`);

const names = (source: string) =>
    [...source.matchAll(/^\s*name: *"([^"]*)"/gm)].map(match => match[1]);
const keys = (source: string, collection: string) =>
    [...source.matchAll(new RegExp(`${collection}\\["([^"]+)"\\] *=`, "g"))].map(match => match[1]);

// Every collection whose ids reach a save. Skills and stances are left out on
// purpose: saves key them by skill_id and by ids like MB_Power, so their
// translated display names were never identity.
const sources: [string, (source: string) => string[]][] = [
    ["items.js", names],
    ["enemies.js", names],
    ["locations.js", names],
    // These two had their keys renamed as well, and key and name are the same
    // string in both, so the keys are covered by pairing names.
    ["active_effects.js", names],
    ["traders.js", source => keys(source, "traders")],
];

const map: Record<string, string> = {};
const report: string[] = [];

for(const [file, extract] of sources) {
    const zh = extract(show(base, file));
    const en = extract(show(BRANCH, file));
    if(zh.length !== en.length) {
        throw new Error(`${file}: ${zh.length} names at the base, ${en.length} on ${BRANCH}, cannot pair by position`);
    }

    let renamed = 0;
    for(let i = 0; i < zh.length; i++) {
        if(en[i] === zh[i]) continue;
        // A later id may reuse an earlier English string; first claim wins, and
        // a conflict means the pairing drifted rather than that both are right.
        if(map[en[i]] && map[en[i]] !== zh[i]) {
            console.warn(`  ${file}: "${en[i]}" claimed by both ${map[en[i]]} and ${zh[i]}, keeping the first`);
            continue;
        }
        map[en[i]] = zh[i];
        renamed++;
    }
    report.push(`  ${file}: ${renamed} renamed of ${zh.length}`);
}

const body = Object.keys(map)
    .sort()
    .map(en => `    ${JSON.stringify(en)}: ${JSON.stringify(map[en])},`)
    .join("\n");

mkdirSync(join(root, "src/i18n/en"), { recursive: true });
writeFileSync(
    join(root, "src/i18n/en/save_ids.js"),
    `// Generated by tools/generate-save-ids.ts from ${BRANCH} against ${base.slice(0, 7)}.\n` +
    `// Do not edit. English -> Chinese for ids that can appear in an old English save.\n` +
    `export const foreign_ids = {\n${body}\n};\n`,
);

console.log(report.join("\n"));
console.log(`generate-save-ids: ${Object.keys(map).length} ids`);
